# Generated by Django 2.1 on 2018-12-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goods_county',
            new_name='goods_country',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='county_name',
            new_name='country_name',
        ),
    ]
