# Generated by Django 2.1 on 2018-12-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goods',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goods_county',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_info.country'),
        ),
        migrations.AlterField(
            model_name='goods_county',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_info.goods'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
