# Generated by Django 2.1 on 2018-12-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods_info', '0002_auto_20181210_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_country',
            name='country',
            field=models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, to='goods_info.country'),
        ),
        migrations.AlterField(
            model_name='goods_country',
            name='goods',
            field=models.ForeignKey(db_column='goods', on_delete=django.db.models.deletion.CASCADE, to='goods_info.goods'),
        ),
    ]
