# Generated by Django 2.1 on 2018-12-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_info', '0004_auto_20181212_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_country',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='goods_country',
            name='goods',
            field=models.CharField(max_length=255),
        ),
    ]
